name: HTML

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install wheel and pyLODE 
      run: pip install wheel pylode
    - name: Install requests and argparse 
      run: pip install requests argparse
    - name: Upload to Ontodocker
      run: scripts/tiny-uploader/tiny-uploader.py -u https://ontodocker.material-digital.de -d ci-experiment -t core_tensile_test_data.ttl -j ${{ upload-jwt.UPLOAD_SECRET }}
    - name: Build HTML
      run: echo "TODO-validate-ttl" && mkdir -p public && pylode -i core_tensile_test_data.ttl -o public/index.html
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
